name: auto-update-proxy-url
on: [push]
jobs: 
  update-proxy-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |  
          echo 'Hello World!' >> testfile.txt
          git config --local user.email "test@github.com"
          git config --local user.name "GitHub Action test"
          git add .
          git commit -m "add changes"

      