name: Update backend URL referenced in frontend code
on: 
  push:
    branches:
      - main
jobs: 
  update-proxy-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # https://stackoverflow.com/questions/8123674/how-to-git-commit-nothing-without-an-error
      - run: |  
          python ./.github/workflows/switchToProdCode.py
          git config --local user.email "leonzh2k@gmail.com"
          git config --local user.name "leonzh2k"
          git add .
          git diff-index --quiet HEAD || git commit -m 'switch to prod env vars' && git push

      